`timescale 1ns / 1ps
// sim_nn_rgb.v
// Converted from sim_nn_rgb.vhd
// FPGA Vision Remote Lab - Marco Winzker, H-BRS
//
// Testbench: reads a PPM image (stimuli), drives nn_rgb, writes output PPM.
// Requires: image_stimuli.ppm in the simulation run directory (or update paths below).
//
// Note: Verilog file I/O uses $fopen/$fscanf/$fwrite instead of VHDL textio.
//       PPM P3 format is plain-text RGB triplets.
 
module sim_nn_rgb;
 
    // ---- Simulation parameters ----
    parameter STIMULI_FILE  = "image_stimuli.ppm";
    parameter RESPONSE_FILE = "image_response.ppm";
    parameter X_BLANK       = 100;
    parameter TRAIL         = 1000;
 
    // ---- DUT signals ----
    reg        clk       = 0;
    reg        reset_n;
    reg  [2:0] enable_in;
    reg        vs_in, hs_in, de_in;
    reg  [7:0] r_in,  g_in,  b_in;
    wire       vs_out, hs_out, de_out;
    wire [7:0] r_out,  g_out,  b_out;
    wire       clk_o;
    wire [2:0] led;
 
    // ---- Image dimensions (read from PPM header) ----
    integer x_size, y_size;
    integer end_tb = 0;
 
    // ---- Clock: 100 MHz (10 ns period) ----
    always #5 clk = ~clk;
 
    // ---- DUT instantiation ----
    nn_rgb duv (
        .clk       (clk),
        .reset_n   (reset_n),
        .enable_in (enable_in),
        .vs_in     (vs_in),  .hs_in (hs_in),  .de_in (de_in),
        .r_in      (r_in),   .g_in  (g_in),   .b_in  (b_in),
        .vs_out    (vs_out), .hs_out(hs_out), .de_out(de_out),
        .r_out     (r_out),  .g_out (g_out),  .b_out (b_out),
        .clk_o     (clk_o),
        .led       (led)
    );
 
    // =========================================================
    // Stimuli process
    // =========================================================
    integer stimuli_fd;
    integer r_int, g_int, b_int;
    integer x, y, i;
    reg [255:0] line_buf;   // scratch line buffer for header reads
 
    initial begin
        // Open stimuli file
        stimuli_fd = $fopen(STIMULI_FILE, "r");
        if (stimuli_fd == 0) begin
            $display("ERROR: Cannot open stimuli file: %s", STIMULI_FILE);
            $finish;
        end
 
        // Read PPM header (4 lines: magic, comment, width height, maxval)
        $fgets(line_buf, stimuli_fd);   // P3
        $fgets(line_buf, stimuli_fd);   // comment
        $fscanf(stimuli_fd, "%d %d\n", x_size, y_size);
        $fgets(line_buf, stimuli_fd);   // 255
 
        // Initialise signals
        reset_n   = 0;
        enable_in = 3'b111;
        vs_in = 0; hs_in = 0; de_in = 0;
        r_in  = 0; g_in  = 0; b_in  = 0;
 
        // Reset for 10 clock cycles
        #100;
        reset_n = 1;
 
        // One frame
        for (y = 0; y < y_size; y = y + 1) begin
 
            // Vertical sync on first line
            vs_in = (y == 0) ? 1 : 0;
 
            // Horizontal blanking
            hs_in = 1;
            for (i = 0; i < X_BLANK; i = i + 1)
                @(negedge clk);
            hs_in = 0;
 
            // Active pixels
            de_in = 1;
            for (x = 0; x < x_size; x = x + 1) begin
                $fscanf(stimuli_fd, "%d %d %d", r_int, g_int, b_int);
                r_in = r_int[7:0];
                g_in = g_int[7:0];
                b_in = b_int[7:0];
                @(negedge clk);
            end
            de_in = 0;
            r_in  = 0; g_in = 0; b_in = 0;
        end
 
        // Trailing cycles
        for (i = 0; i < TRAIL; i = i + 1)
            @(negedge clk);
 
        end_tb = 1;
        $fclose(stimuli_fd);
        #20;
 
        $display("Simulation completed");
        $finish;
    end
 
    // =========================================================
    // Response process - write output image to PPM file
    // =========================================================
    integer response_fd;
    integer r_sim, g_sim, b_sim;
 
    initial begin
        // Wait until stimuli process starts (hs_out goes high)
        @(posedge hs_out);
 
        response_fd = $fopen(RESPONSE_FILE, "w");
        if (response_fd == 0) begin
            $display("ERROR: Cannot open response file: %s", RESPONSE_FILE);
            $finish;
        end
 
        // Write PPM header
        $fwrite(response_fd, "P3\n");
        $fwrite(response_fd, "# generated by Verilog testbench\n");
        $fwrite(response_fd, "%0d %0d\n", x_size, y_size);
        $fwrite(response_fd, "255\n");
 
        while (end_tb != 1) begin
            @(negedge clk);
            if (de_out == 1) begin
                r_sim = r_out;
                g_sim = g_out;
                b_sim = b_out;
                $fwrite(response_fd, "%0d %0d %0d\n", r_sim, g_sim, b_sim);
            end
        end
 
        $fclose(response_fd);
    end
 
endmodule